[package]
name = "bitcoin_contract"
version = "0.1.0"
authors = ["Davidson Souza <davidson.lucas.souza@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.27.0"